"""empty message

Revision ID: 165ab501a1b4
Revises: 49bb75ee4c10
Create Date: 2023-01-09 17:09:08.773415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '165ab501a1b4'
down_revision = '49bb75ee4c10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.drop_constraint('tabla_clasificadora_articulo_key', type_='unique')
        batch_op.drop_constraint('tabla_clasificadora_jaulas_key', type_='unique')
        batch_op.drop_constraint('tabla_clasificadora_lote_key', type_='unique')
        batch_op.drop_constraint('tabla_clasificadora_pedido_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.create_unique_constraint('tabla_clasificadora_pedido_key', ['pedido'])
        batch_op.create_unique_constraint('tabla_clasificadora_lote_key', ['lote'])
        batch_op.create_unique_constraint('tabla_clasificadora_jaulas_key', ['jaulas'])
        batch_op.create_unique_constraint('tabla_clasificadora_articulo_key', ['articulo'])

    # ### end Alembic commands ###
