"""empty message

Revision ID: 49bb75ee4c10
Revises: 8ee0c70f0329
Create Date: 2023-01-09 16:35:35.401151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49bb75ee4c10'
down_revision = '8ee0c70f0329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.drop_constraint('tabla_clasificadora_turno_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.create_unique_constraint('tabla_clasificadora_turno_key', ['turno'])

    # ### end Alembic commands ###
