"""empty message

Revision ID: 523f11fde5db
Revises: 267236ac53ff
Create Date: 2022-12-22 19:32:30.592643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523f11fde5db'
down_revision = '267236ac53ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.drop_constraint('tabla_clasificadora_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('tabla_clasificadora_user_id_fkey', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
