"""empty message

Revision ID: 5999aa249479
Revises: 534db2a465b7
Create Date: 2023-01-02 12:22:54.363826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5999aa249479'
down_revision = '534db2a465b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['id'])

    with op.batch_alter_table('tabla_mecanico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horas', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('fecha', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_mecanico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('fecha')
        batch_op.drop_column('horas')

    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
