"""empty message

Revision ID: 63187ea424d0
Revises: fef630e2c60d
Create Date: 2023-01-03 11:30:44.746999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63187ea424d0'
down_revision = 'fef630e2c60d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turno', sa.String(), nullable=True))
        batch_op.drop_column('work_shift')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_shift', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('turno')

    # ### end Alembic commands ###
