"""empty message

Revision ID: 6656d9b5ae39
Revises: 41fc65e716b1
Create Date: 2022-12-22 18:11:20.457526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6656d9b5ae39'
down_revision = '41fc65e716b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.drop_column('id_tabla')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_tabla', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
