"""empty message

Revision ID: 8ee0c70f0329
Revises: 63187ea424d0
Create Date: 2023-01-06 16:01:56.527218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ee0c70f0329'
down_revision = '63187ea424d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turno', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['turno'])

    with op.batch_alter_table('tabla_mecanico', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turno', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['turno'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('turno')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('turno', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('tabla_mecanico', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('turno')

    with op.batch_alter_table('tabla_clasificadora', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('turno')

    # ### end Alembic commands ###
