"""empty message

Revision ID: d4f108407bd1
Revises: dc9a9ae90961
Create Date: 2023-01-11 07:36:59.469799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f108407bd1'
down_revision = 'dc9a9ae90961'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tabla_rechazo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fichas', sa.Float(), nullable=True),
    sa.Column('paneles', sa.Float(), nullable=True),
    sa.Column('jaula', sa.Float(), nullable=True),
    sa.Column('turno', sa.String(), nullable=True),
    sa.Column('fecha', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('tabla_mecanico', schema=None) as batch_op:
        batch_op.drop_constraint('tabla_mecanico_accion_key', type_='unique')
        batch_op.drop_constraint('tabla_mecanico_problema_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_mecanico', schema=None) as batch_op:
        batch_op.create_unique_constraint('tabla_mecanico_problema_key', ['problema'])
        batch_op.create_unique_constraint('tabla_mecanico_accion_key', ['accion'])

    op.drop_table('tabla_rechazo')
    # ### end Alembic commands ###
