"""empty message

Revision ID: dc9a9ae90961
Revises: 165ab501a1b4
Create Date: 2023-01-09 17:16:10.449996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9a9ae90961'
down_revision = '165ab501a1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_mecanico', schema=None) as batch_op:
        batch_op.drop_constraint('tabla_mecanico_turno_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tabla_mecanico', schema=None) as batch_op:
        batch_op.create_unique_constraint('tabla_mecanico_turno_key', ['turno'])

    # ### end Alembic commands ###
