"""empty message

Revision ID: fef630e2c60d
Revises: 77fdcef7be44
Create Date: 2023-01-03 11:15:18.231010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fef630e2c60d'
down_revision = '77fdcef7be44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_shift', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('work_shift')

    # ### end Alembic commands ###
